# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commssion_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_us', models.FloatField()),
                ('exchange_rate_uk', models.FloatField()),
                ('exchange_rate_de', models.FloatField()),
                ('exchange_rate_au', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='First_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_class_us', models.FloatField()),
                ('first_class_uk', models.FloatField()),
                ('first_class_de', models.FloatField()),
                ('first_class_au', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GZ_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gz_us', models.FloatField()),
                ('gz_uk', models.FloatField()),
                ('gz_de', models.FloatField()),
                ('gz_au', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Second_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_class_us', models.FloatField()),
                ('second_class_uk', models.FloatField()),
                ('second_class_de', models.FloatField()),
                ('second_class_au', models.FloatField()),
            ],
        ),
    ]
