# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20170331_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_class_us', models.FloatField()),
                ('first_class_uk', models.FloatField()),
                ('first_class_de', models.FloatField()),
                ('first_class_au', models.FloatField()),
                ('second_class_us', models.FloatField()),
                ('second_class_uk', models.FloatField()),
                ('second_class_de', models.FloatField()),
                ('second_class_au', models.FloatField()),
                ('gz_us', models.FloatField()),
                ('gz_uk', models.FloatField()),
                ('gz_de', models.FloatField()),
                ('gz_au', models.FloatField()),
                ('exchange_rate_us', models.FloatField()),
                ('exchange_rate_uk', models.FloatField()),
                ('exchange_rate_de', models.FloatField()),
                ('exchange_rate_au', models.FloatField()),
                ('commission_rate', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Commssion_rate',
        ),
        migrations.DeleteModel(
            name='Exchange_Rate',
        ),
        migrations.DeleteModel(
            name='First_Class',
        ),
        migrations.DeleteModel(
            name='GZ_Class',
        ),
        migrations.DeleteModel(
            name='Second_Class',
        ),
    ]
